name: Release

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Write version to env
        run: |
          echo "new_event_processor_version=$(inv get-latest)" >> $GITHUB_ENV
      - name: Update version file
        run: echo "${{ env.new_event_processor_version }}" > VERSION
      - name: Package
        run: inv clean package
      - name: Publish
        env:
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
        run: inv publish --pypi-url="${{ secrets.pypi_url }}"
      - name: Open VERSION bump PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update version to ${{ env.new_event_processor_version }}
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: bump-version/${{ env.new_event_processor_version }}
          delete-branch: true
          base: main
          title: Update VERSION to ${{ env.new_event_processor_version }}
          body: A new version of the project has been released, so the `VERSION` file should be updated accordingly.
